"""climate table

Revision ID: 6efe133ec137
Revises: 4bf46def96ec
Create Date: 2018-02-21 15:51:40.235442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6efe133ec137'
down_revision = '4bf46def96ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rainfall_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rainfall', sa.String(length=128), nullable=True),
    sa.Column('climate_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['climate_id'], ['climate_data.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('temperature_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('temperature', sa.String(length=120), nullable=True),
    sa.Column('climate_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['climate_id'], ['climate_data.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_climate_data_date'), 'climate_data', ['date'], unique=True)
    op.drop_column('climate_data', 'rainfall')
    op.drop_column('climate_data', 'temperature')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('climate_data', sa.Column('temperature', sa.VARCHAR(length=120), nullable=True))
    op.add_column('climate_data', sa.Column('rainfall', sa.VARCHAR(length=128), nullable=True))
    op.drop_index(op.f('ix_climate_data_date'), table_name='climate_data')
    op.drop_table('temperature_data')
    op.drop_table('rainfall_data')
    # ### end Alembic commands ###
